---
# THIS IS A SAMPLE ".tas.yml" CONFIGURATION FILE
#
# supported frameworks: mocha|jest|jasmine
framework: jest
tier: large
blocklist:
  - "./scripts/error-codes/__tests__/invertObject-test.js##invertObject##should return an empty object for an empty input"
preRun:
  # set of commands to run before running the tests
  # for eg `yarn install`, `yarn build`
  command:
    # For eg, npm ci, yarn install
    - yarn

postMerge:
  # glob-pattern for identifying the test files
  env:
    NODE_ENV: development
    npm_lifecycle_event: test
    INTVALUE: ${{ secrets.Int_value }}
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
configFile: scripts/jest/config.source-www.js
nodeVersion: 14.17.6
version: 1.0.1
