---
# THIS IS A SAMPLE ".tas.yml" CONFIGURATION FILE
#
# supported frameworks: mocha|jest|jasmine
framework: jest

preRun:
  # set of commands to run before running the tests
  # for eg `yarn install`, `yarn build`
  command:
    # change the command according to the package manager used.
    # For eg, npm ci, yarn install
    - yarn

postMerge:
  # glob-pattern for identifying the test files
  env:
    NODE_ENV: development
    npm_lifecycle_event: test
  pattern:
    # glob-patterns to discover tests to run in case of postMerge
    # - "./unit_test_folder_A/**/*.spec.ts"
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
configFile: scripts/jest/config.source-www.js
nodeVersion: 14.17.6
