---
framework: jest
<<<<<<< HEAD
=======
blocklist:
  - "./scripts/error-codes/__tests__/invertObject-test.js##invertObject##should return an empty object for an empty input"
preRun:
  # set of commands to run before running the tests
  # for eg `yarn install`, `yarn build`
  command:
    # For eg, npm ci, yarn install
    - yarn

>>>>>>> Update .tas.yml
postMerge:
  # glob-pattern for identifying the test files
  env:
      NODE_ENV: development
      npm_lifecycle_event: test
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
preMerge:
  env:
    NODE_ENV: development
    npm_lifecycle_event: test
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
preRun:
  command:
    - yarn install --frozen-lockfile
postRun:
  command:
    - node --version
configFile: scripts/jest/config.source-www.js
nodeVersion: 14.17.6
parallelism: 2
splitMode: file
version: 1.0.1
